(use-package hy-mode)
(define-key hy-mode-map (kbd "\C-cb") 'hy-shell-eval-buffer)
(define-key hy-mode-map (kbd "\C-cc") 'hy-shell-eval-current-form)
(define-key hy-mode-map (kbd "\C-cl") 'hy-shell-eval-last-sexp)
(define-key hy-mode-map (kbd "\C-cr") 'hy-shell-eval-region)
