(load "~/.emacs.d/config/package-manager.el")
(load "~/.emacs.d/config/customize.el")
(load "~/.emacs.d/config/mail/config.el")
(load "~/.emacs.d/config/theme/config.el")
(load "~/.emacs.d/config/git/config.el")
(load "~/.emacs.d/config/company/config.el")
(load "~/.emacs.d/config/lsp/config.el")
(load "~/.emacs.d/config/eaf/config.el")

(load "~/.emacs.d/config/c-c++/config.el")
(load "~/.emacs.d/config/java/config.el")
(load "~/.emacs.d/config/hy/config.el")
(load "~/.emacs.d/config/python/config.el")
(load "~/.emacs.d/config/web/config.el")
(load "~/.emacs.d/config/commonlisp/config.el")
